# Generated by Django 2.0.5 on 2018-06-02 19:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0002_auto_20180531_1015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias',
            new_name='News',
        ),
    ]
